# 该文件用于演示所有可用参数,请以此为蓝本裁剪自己专属的空洞配置
auto_battle: 全配队通用
region_type_priority:
- 战斗-武备
- 挑战-无伤
- 挑战-限时
- 邦布商店
- 挚交会谈
- 战斗-硬币
- 战斗-鸣徽
- 战斗-道中危机
- 战斗-终结之役
artifact_priority:
- 机敏
- 终结
- 通用
- 绝境
- 契合
- 异常·击破
- 星见雅
- 艾莲
- 月城柳
- 比利
- 卡牌
- 无详情 获得鸣徽
buy_only_priority: 2
period_buff_no: 第一个