from one_dragon.base.geometry.point import Point

STANDARD_WIDTH = 1920
STANDARD_HEIGHT = 1080
STANDARD_CENTER_POS = Point(STANDARD_WIDTH // 2, STANDARD_HEIGHT // 2)

YOLO_DEFAULT_COLOR = (114, 114, 114)
